export const STAKE_TOKEN_ADDRESSES = "ENTER CONTRACT ADRESS HERE";

export const REWARD_TOKEN_ADDRESSES = "ENTER CONTRACT ADRESS HERE";

export const STAKE_CONTRACT_ADDRESSES = "ENTER CONTRACT ADRESS HERE";

